{{- if and .Values.config.starrocks.password (not .Values.config.starrocks.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermeneus.fullname" . }}
  labels:
    {{- include "hermeneus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.starrocks.existingSecretKey }}: {{ .Values.config.starrocks.password | quote }}
{{- end -}}
