apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermeneus.fullname" . }}
  labels:
    {{- include "hermeneus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ch-native
      port: {{ .Values.service.port }}
      targetPort: ch-native
      protocol: TCP
  selector:
    {{- include "hermeneus.selectorLabels" . | nindent 4 }}
